name: Deploy

on:
  release:
    types:
      - published
  workflow_call:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying..."
